### 1. 事件循环

#### 1.1 值透传

```javascript
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)
// 1
// Promise {<fulfilled>: undefined}
```

Promise.resolve方法的参数如果是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的Promise对象，状态为resolved，Promise.resolve方法的参数，会同时传给回调函数。

then方法接受的参数是函数，而如果传递的并非是一个函数，它实际上会将其解释为then(null)，这就会导致前一个Promise的结果会传递下面。

#### 1.2 return new Error

```javascript
Promise.resolve().then(() => {
  return new Error('error!!!')
}).then(res => {
  console.log("then: ", res)
}).catch(err => {
  console.log("catch: ", err)
})
// then: Error: error!!!
```

返回任意一个非 promise 的值都会被包裹成 promise 对象，因此这里的`return new Error('error!!!')`也被包裹成了`return Promise.resolve(new Error('error!!!'))`，因此它会被then捕获而不是catch。

#### 1.3 错误捕获

```javascript
Promise.reject('err!!!')
  .then((res) => {
    console.log('success', res)
  }, (err) => {
    console.log('error', err)
  }).catch(err => {
    console.log('catch', err)
  })
```

错误被`then`的第二个参数捕获了，就不会被`catch`捕获了

```javascript
Promise.resolve()
  .then(function success (res) {
    throw new Error('error!!!')
  }, function fail1 (err) {
    console.log('fail1', err)
  }).catch(function fail2 (err) {
    console.log('fail2', err)
  })
```

在then中抛出的错误只会被`catch`捕获

#### 1.4 async

```javascript
async function async1() {
  console.log("async1 start");
  await async2();
  console.log("async1 end");
}
async function async2() {
  console.log("async2");
}
async1();
console.log('start')
// aysnc1 start 
// async2
// start
// async1 end
```

1. 首先执行函数中的同步代码`async1 start`，之后遇到了`await`，它会阻塞`async1`后面代码的执行，因此会先去执行`async2`中的同步代码`async2`，然后跳出`async1`；
2. 跳出`async1`函数后，执行同步代码`start`；
3. 在一轮宏任务全部执行完之后，再来执行`await`后面的内容`async1 end`。

**这里可以理解为await后面的语句相当于放到了new Promise中，下一行及之后的语句相当于放在Promise.then中。**

### 2. this

#### 2.1 arguments

```javascript
var length = 10;
function fn() {
    console.log(this.length);
}
 
var obj = {
  length: 5,
  method: function(fn) {
    fn();
    arguments[0]();
  }
};
 
obj.method(fn, 1); // 10 2
```

1. 第一次执行fn()，this指向window对象，输出10。
2. 第二次执行arguments[0](https://link.juejin.cn/?target=)，相当于arguments调用方法，this指向arguments，而这里传了两个参数，故输出arguments长度为2。

### 3. 作用域

#### 3.1 var x = y = 1

```javascript
(function(){
   var x = y = 1;
})();
var z;

console.log(y); // 1
console.log(z); // undefined
console.log(x); // Uncaught ReferenceError: x is not defined
```

这段代码的关键在于：var x = y = 1; 实际上这里是从右往左执行的，首先执行y = 1, 因为y没有使用var声明，所以它是一个全局变量，然后第二步是将y赋值给x，讲一个全局变量赋值给了一个局部变量，最终，x是一个局部变量，y是一个全局变量，所以打印x是报错。

#### 3.2 变量提升

```javascript
var friendName = 'World';
(function() {
  if (typeof friendName === 'undefined') {
    // 变量提升
    var friendName = 'Jack';
    console.log('Goodbye ' + friendName);
  } else {
    console.log('Hello ' + friendName);
  }
})();
// Goodbye Jack
```

### 4. 原型链与继承

- Object.prototype是原型链的终点，具有toString()、valueOf()等函数，Object.prototype.\_proto\_ =null
- Function是所有函数的构造函数，所有函数是Function的实例，Person.\_proto\_ = Function.prototype; Function自身也是自己的一个实例，Function.\_proto_ = Function.prototype; 
- Function也是一个对象，Function.prototype.\_proto_ = Object.prototype; Object也是Function的一个实例，Object.\_proto_ = Function.prototype

![image-20220210122738185](https://picture-1305610595.cos.ap-guangzhou.myqcloud.com/202206041454096.png)